/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Concurrent;
using System.Net.Http;
using AuthenticationSdk.core;
using AuthenticationSdk.util;
using RestSharp;

namespace CyberSource.Client
{
    /// <summary>
    /// Factory for creating and caching RestClient instances with specific configurations.
    /// Uses a concurrent dictionary to cache RestClient instances based on configuration hash codes,
    /// reducing overhead when multiple requests use the same network configuration.
    /// Supports lazy initialization of HttpClient and RestClient instances.
    /// </summary>
    internal static class RestClientFactory
    {
        /// <summary>
        /// Thread-safe cache of RestClient instances indexed by configuration hash code.
        /// Each RestClient is wrapped in a Lazy instance to defer creation until first use.
        /// </summary>
        private static readonly ConcurrentDictionary<int, Lazy<RestClient>> _restClientInstances = new ConcurrentDictionary<int, Lazy<RestClient>>();

        #region NEW METHODS
        /// <summary>
        /// Gets or creates a cached RestClient instance configured with the specified merchant network settings and client options.
        /// Uses configuration parameters to generate a unique hash for caching, ensuring that clients with identical
        /// configurations reuse the same RestClient instance.
        /// </summary>
        /// <param name="merchantNetworkSettings">The merchant network settings containing timeout, connection pool size, and keep-alive configuration.</param>
        /// <param name="clientOptions">The RestClient options including base URL, proxy, and user agent settings.</param>
        /// <returns>A RestClient instance configured with the specified settings, either from cache or newly created.</returns>
        public static RestClient GetRestClient(IMerchantNetworkSettings merchantNetworkSettings, RestClientOptions clientOptions)
        {
            // Parse configuration values with null-safety
            int timeout = merchantNetworkSettings?.TimeOut != null
                ? merchantNetworkSettings.TimeOut
                : int.Parse(Constants.DEFAULT_TIME_OUT);

            int defaultConnectionLimit = merchantNetworkSettings?.MaxConnectionPoolSize != null
                ? int.Parse(merchantNetworkSettings.MaxConnectionPoolSize)
                : int.Parse(Constants.DefaultMaxConnectionPoolSize);

            int maxServicePointIdleTime = merchantNetworkSettings?.KeepAliveTime != null
                ? int.Parse(merchantNetworkSettings.KeepAliveTime)
                : int.Parse(Constants.DefaultKeepAliveTime);

            // Include all configuration parameters in hash calculation
            int hash = GetHashOfRestClientOptions(clientOptions, timeout, defaultConnectionLimit, maxServicePointIdleTime);

            // Defer HttpClient creation until actually needed (inside Lazy)
            var lazyClient = _restClientInstances.GetOrAdd(
                hash,
                _ => new Lazy<RestClient>(() =>
                {
                    var handler = new StandardSocketsHttpHandler
                    {
                        PooledConnectionIdleTimeout = TimeSpan.FromMilliseconds(maxServicePointIdleTime),
                        MaxConnectionsPerServer = defaultConnectionLimit
                    };

                    var httpClient = new HttpClient(handler);
                    httpClient.Timeout = TimeSpan.FromMilliseconds(timeout);

                    return new RestClient(httpClient, clientOptions);
                }));

            return lazyClient.Value;
        }
        #endregion

        /// <summary>
        /// Gets or creates a cached RestClient instance configured with the specified merchant configuration and client options.
        /// Legacy method that works with MerchantConfig. Uses configuration parameters to generate a unique hash for caching.
        /// </summary>
        /// <param name="merchantConfig">The merchant configuration containing timeout, connection pool size, and keep-alive settings.</param>
        /// <param name="clientOptions">The RestClient options including base URL, proxy, and user agent settings.</param>
        /// <returns>A RestClient instance configured with the specified settings, either from cache or newly created.</returns>
        public static RestClient GetRestClient(MerchantConfig merchantConfig, RestClientOptions clientOptions)
        {
            // Parse configuration values with null-safety
            int timeout = merchantConfig?.TimeOut != null 
                ? int.Parse(merchantConfig.TimeOut) 
                : int.Parse(Constants.DEFAULT_TIME_OUT);
            
            int defaultConnectionLimit = merchantConfig?.MaxConnectionPoolSize != null
                ? int.Parse(merchantConfig.MaxConnectionPoolSize)
                : int.Parse(Constants.DefaultMaxConnectionPoolSize);
            
            int maxServicePointIdleTime = merchantConfig?.KeepAliveTime != null
                ? int.Parse(merchantConfig.KeepAliveTime)
                : int.Parse(Constants.DefaultKeepAliveTime);

            // Include all configuration parameters in hash calculation
            int hash = GetHashOfRestClientOptions(clientOptions, timeout, defaultConnectionLimit, maxServicePointIdleTime);

            // Defer HttpClient creation until actually needed (inside Lazy)
            var lazyClient = _restClientInstances.GetOrAdd(
                hash,
                _ => new Lazy<RestClient>(() =>
                {
                    var handler = new StandardSocketsHttpHandler
                    {
                        PooledConnectionIdleTimeout = TimeSpan.FromMilliseconds(maxServicePointIdleTime),
                        MaxConnectionsPerServer = defaultConnectionLimit
                    };

                    var httpClient = new HttpClient(handler);
                    httpClient.Timeout = TimeSpan.FromMilliseconds(timeout);

                    return new RestClient(httpClient, clientOptions);
                }));

            return lazyClient.Value;
        }

        /// <summary>
        /// Generates a hash code for the specified RestClient configuration parameters.
        /// The hash code is used to uniquely identify a configuration and enable caching of RestClient instances
        /// with the same configuration.
        /// </summary>
        /// <param name="clientOptions">The RestClient options including base URL, certificates, proxy, and user agent.</param>
        /// <param name="timeout">The HTTP connection timeout in milliseconds.</param>
        /// <param name="connectionLimit">The maximum number of concurrent connections per server.</param>
        /// <param name="idleTime">The time in milliseconds to keep idle connections alive before closing.</param>
        /// <returns>A hash code representing the combined configuration parameters.</returns>
        private static int GetHashOfRestClientOptions(RestClientOptions clientOptions, int timeout, int connectionLimit, int idleTime)
        {
            // Include all configuration parameters in hash to avoid collisions
            return HashCode.Combine(
                clientOptions.BaseUrl,
                clientOptions.ClientCertificates,
                clientOptions.Proxy,
                clientOptions.UserAgent,
                timeout,
                connectionLimit,
                idleTime
            );
        }
    }
}
