name: CyberSource AuthenticationSDK Build

on:
  push:

jobs:
  build:
    runs-on: windows-2022
    name: build
    steps:
    - name: Support longpaths
      run: git config --system core.longpaths true
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore cybersource-rest-auth-netstandard\AuthenticationSdk\AuthenticationSdk.sln
    - name: Build
      run: dotnet build cybersource-rest-auth-netstandard\AuthenticationSdk\AuthenticationSdk.sln -c Release --no-restore

