name: CyberSource AuthenticationSDK Build

on:
  push:

jobs:
  build:
    runs-on: windows-2022
    name: build
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore cybersource-rest-auth-netstandard\AuthenticationSdk\AuthenticationSdk.csproj
    - name: Build
      run: dotnet build cybersource-rest-auth-netstandard\AuthenticationSdk\AuthenticationSdk.csproj -c Release --no-restore

